version: "3"
services:
  app:
    build: ./docker/php
    depends_on:
      - db
    # links:
    #   - db
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  web:
    # image: nginx
    build: ./docker/nginx
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    #   - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    # links:
    #   - app

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=laraveldb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    # container_name: db-host

volumes:
  db-store:
